; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Ink Canvas Ultra"
#define MyAppVersion "26.9.2"
#define MyAppPublisher "muqiu-pika"
#define MyAppURL "https://github.com/muqiu-pika/Ink-Canvas-Ultra"
#define MyAppExeName "Ink Canvas Ultra.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt1 ".icart"
#define MyAppAssocExt2 ".icstk"
#define MyAppAssocKey1 StringChange(MyAppAssocName, " ", "") + MyAppAssocExt1
#define MyAppAssocKey2 StringChange(MyAppAssocName, " ", "") + MyAppAssocExt2

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{69D2B507-FAB8-4C81-A597-F36263C6A25E}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\{#MyAppName}
; 使用按用户安装目录（localappdata\Programs）：无需管理员权限，静默更新不会触发 UAC 弹窗。
; 若要恢复为全机安装，请改回 {autopf}\{#MyAppName}（但静默更新将因需要提权而无法后台完成）。
ChangesAssociations=yes
DisableProgramGroupPage=yes
; 静默更新时让 Inno 主动关闭正在运行的应用（配合 /CLOSEAPPLICATIONS 命令行参数），
; 避免主程序 exe 被占用导致安装降级为"重启后替换"（下次打开仍是旧版本）。
CloseApplications=yes
; 与 App.xaml.cs 的单实例互斥体同名，安装器据此识别并关闭正在运行的 Ink Canvas Ultra。
AppMutex=Ink_Canvas_Ultra
; 关闭应用后不自动重启（由 [Run] 段的 postinstall 启动新版本，避免重复拉起）。
RestartApplications=no
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=dist
#define OutputBaseFilename "Ink.Canvas.Ultra.V" + MyAppVersion + ".Setup"
OutputBaseFilename={#OutputBaseFilename}
SetupIconFile=Ink Canvas\Resources\Ink Canvas Ultra.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinese"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[CustomMessages]
english.automaticallyDoApps=Automatically configure the applications
chinese.automaticallyDoApps=自动配置应用程序

[Tasks]
Name: automaticallyDoApps; Description: "{cm:automaticallyDoApps}"
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone
//Flags: unchecked

[Files]
Source: "Ink Canvas\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; 插件（Plugins 目录）不随安装包分发：文档转照片等需要安装插件才能运行的功能已全部迁移到插件中，
; 用户在安装后可从「插件工坊」按需在线下载安装，从而显著减小安装包体积。
; 排除 *.vbs：视频展台已插件化，旧的「视频展台.vbs」启动脚本不再随包分发，
; 改由插件启用时直接在桌面创建指向主程序（--video-presenter）的快捷方式。
Source: "Ink Canvas\bin\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "Plugins,*.vbs"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; First file extension
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt1}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey1}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey1}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey1}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey1}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName} %1"
; Second file extension
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt2}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey2}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey2}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey2}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey2}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName} %1"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autoprograms}\视频展台"; Filename: "{app}\{#MyAppExeName}"; Parameters: "--video-presenter"; WorkingDir: "{app}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[UninstallDelete]
; 桌面的「视频展台」快捷方式由插件运行时创建（不属于 [Icons] 条目），
; Inno 卸载时不会自动清理，必须在此显式删除，否则卸载后会残留一个无效快捷方式。
; 必须用 {userdesktop} 而非 {autodesktop}：代码侧使用 Environment.SpecialFolder.Desktop（当前用户桌面），
; 而 {autodesktop} 在管理员安装模式下会解析为公共桌面 {commondesktop}，二者不一致将导致快捷方式残留。
Type: files; Name: "{userdesktop}\视频展台.lnk"
; 旧版本曾随包分发「视频展台.vbs」启动脚本，此处清理升级后遗留的旧文件。
Type: files; Name: "{app}\视频展台.vbs"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall
